### ISSUE TITLE
 Cannot parse path: info hash received

### ISSUE THREAD

**Issue by lamireRoma** [sleeyax/stremio-streaming-server#16]
Hi,

I tried to ran the container using this command `docker run -p 11470:11470 -e FIX_CORS=1 -e FIX_UNSUPPORTED_MEDIA=1 -e FORCE_HTTPS=1 -v /media/external/:/root/.stremio-server --name=stremio-streaming-server sleeyax/stremio-streaming-server` and I can see the container is created successfully and the server started too (_see below_). After that I configured my stremio web client to use this new server as the Streaming server ( _see below_). So far everything its fine but when I tried to reproduce any resource I'm having an error in the web client saying `"Video is not supported"` (_see below_) and into the server logs I have this:

```bash
-> POST /17e76561ce358d7d33128c409d3356e7948ffdaf/create
-> HEAD /17e76561ce358d7d33128c409d3356e7948ffdaf/undefined
Error: Cannot parse path: info hash received, but invalid file index or file name
    at /stremio/server.js:46313:41
    at EventEmitter.<anonymous> (/stremio/server.js:46140:58)
    at Object.onceWrapper (events.js:422:26)
    at EventEmitter.emit (events.js:315:20)
    at EventEmitter.emit (domain.js:486:12)
    at /stremio/server.js:46185:35
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
-> HEAD /hlsv2/e6db21b6b4bf66fe5db4dc1e17b8db9d/master.m3u8?mediaURL=http%3A%2F%2F10.0.0.54%3A11470%2F17e76561ce358d7d33128c409d3356e7948ffdaf%2Fundefined&maxAudioChannels=2
-> GET /17e76561ce358d7d33128c409d3356e7948ffdaf/undefined bytes=0-
Error: Cannot parse path: info hash received, but invalid file index or file name
    at /stremio/server.js:46313:41
    at EventEmitter.<anonymous> (/stremio/server.js:46140:58)
    at Object.onceWrapper (events.js:422:26)
    at EventEmitter.emit (events.js:315:20)
    at EventEmitter.emit (domain.js:486:12)
    at /stremio/server.js:46185:35
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
-> GET /hlsv2/e6db21b6b4bf66fe5db4dc1e17b8db9d/master.m3u8?mediaURL=http%3A%2F%2F10.0.0.54%3A11470%2F17e76561ce358d7d33128c409d3356e7948ffdaf%2Fundefined&maxAudioChannels=2 bytes=0-
-> GET /17e76561ce358d7d33128c409d3356e7948ffdaf/undefined bytes=0-
Error: Cannot parse path: info hash received, but invalid file index or file name
    at /stremio/server.js:46313:41
    at EventEmitter.<anonymous> (/stremio/server.js:46140:58)
    at Object.onceWrapper (events.js:422:26)
    at EventEmitter.emit (events.js:315:20)
    at EventEmitter.emit (domain.js:486:12)
    at /stremio/server.js:46185:35
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

```

### Server starting logs
```bash
Forcing HTTPS for serverURL.
Fixing unsupported media issues.
Fixing CORS.
hls executables located ->  { ffmpeg: '/usr/bin/ffmpeg', ffsplit: null }
Using app path -> /root/.stremio-server
Enabling casting...
(node:11) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
EngineFS server started at http://127.0.0.1:11470
EngineFS HTTPS endpoint at https://local.strem.io:12470
-> GET /settings
```

### Streaming Server setup

![image](https://user-images.githubusercontent.com/6482765/192073804-54731d1b-3927-4466-821c-b1a087150cf5.png)

### Stremio Web Error ( Video is not supported)

![image](https://user-images.githubusercontent.com/6482765/192073913-1aca28cf-38b2-426c-b4dc-75cb7a29de67.png)

**Comment by lamireRoma** [comment]
Looks like the problem was the `server.js` version `4.18.0` was the guilty of this problem I checkout the project to rebuild the image and use the latest `https://dl.strem.io/four/master/server.js` ( `v4.19.0`), after that looks like the problem got solve. Here are the logs from the server that started the download

```bash
-> POST /27985e0b649c7c23ae314e844064d837f8afe3c0/create
Engine created for 27985e0b649c7c23ae314e844064d837f8afe3c0
-> HEAD /27985e0b649c7c23ae314e844064d837f8afe3c0/0
-> HEAD /hlsv2/8f4760036da3eb08b35752dcfeb2b587/master.m3u8?mediaURL=http%3A%2F%2F10.0.0.54%3A11470%2F27985e0b649c7c23ae314e844064d837f8afe3c0%2F0&maxAudioChannels=2
-> GET /27985e0b649c7c23ae314e844064d837f8afe3c0/0 bytes=0-
Resizing cache size to 0MB from 0MB by deleting 0 files
-> GET /27985e0b649c7c23ae314e844064d837f8afe3c0/0
Unknown schemaID  0x55b0 tagId= 39 start=515 length=2 source= HttpSource {
  _vints: [],
  _vintsSize: 0,
  configuration: {},
  url: 'http://127.0.0.1:11470/27985e0b649c7c23ae314e844064d837f8afe3c0/0'
}
```

**Comment by sleeyax** [comment]
You also could've deleted the image locally and pull it in again to update it instead of cloning this repo and locally rebuilding it.

**Comment by lamireRoma** [comment]
> You also could've deleted the image locally and pull it in again to update it instead of cloning this repo and locally rebuilding it.

I did that first but looks like the latest image is from a couple months back and have the server.js `4.18.0` that's why I rebuilding it to make sure we have the really `latest` version of that file

**Comment by sleeyax** [comment]
> > You also could've deleted the image locally and pull it in again to update it instead of cloning this repo and locally rebuilding it.
> 
> I did that first but looks like the latest image is from a couple months back and have the server.js `4.18.0` that's why I rebuilding it to make sure we have the really `latest` version of that file

Oh, you are right. I forgot the files are pulled and stored within the docker image itself at build time basically. 

I've been thinking to change the setup of this project a bit and create a entrypoint script to pull dependencies in at runtime instead. I haven't gotten to it yet though.

**Comment by lamireRoma** [comment]
> Owner

That will be the final solution for now you can simply re-run your release action :P and problem solve

**Comment by mikdanjey** [comment]
I got also same issue,  **Please give me a solution**

The server got crashed, while starting the video play.

![image](https://user-images.githubusercontent.com/17296759/210156806-8b92f3ea-ba17-4026-b117-53ce87712b9d.png)
