### ISSUE TITLE
Update the Nodejs version

### ISSUE THREAD

**Issue by mikdanjey** [sleeyax/stremio-streaming-server#18]
in Docker file please use below stable version.

FROM node:16.19.0

**Comment by sleeyax** [comment]
Why? Does this fix anything? I generally 
try to stick to whatever node version Stremio is currently using.

**Comment by sleeyax** [comment]
Hi, the Stremio team has recently announced an **official** docker image: https://github.com/Stremio/server-docker This project will therefore no longer be maintained.
