### ISSUE TITLE
Sharing using https

### ISSUE THREAD

**Issue by g3orgeH** [sleeyax/stremio-streaming-server#22]
Im trying to connect to the server, that is being hosted on oracle clouds server, but i cant get it setup to work over https i wanna use it on the web version on a strict browser which only works with https content.
If there's i dont know a way of customising the https address that gets assigned in the app, or manually setting the IP to the public IP of the server?

**Comment by sleeyax** [comment]
Hi, the Stremio team has recently announced an **official** docker image: https://github.com/Stremio/server-docker This project will therefore no longer be maintained.
