### ISSUE TITLE
Playback Error

### ISSUE THREAD

**Issue by ramkuar0020** [sleeyax/stremio-streaming-server#24]
It shows playback error for most streams.
Only 4k Streams seem to work without error.
But When checking server logs it has loaded the stream and we can acess it from the direct link.
but it doesnt work from the stremio web console.
Video : https://streamable.com/98bccx

**Comment by sleeyax** [comment]
Hi, the Stremio team has recently announced an **official** docker image: https://github.com/Stremio/server-docker This project will therefore no longer be maintained.
