### ISSUE TITLE
Investigate CORS issue with Stremio web

### ISSUE THREAD

**Issue by sleeyax** [sleeyax/stremio-streaming-server#5]
Can't connect to the streaming server on  https://stremio-development.netlify.app/#/settings

See: https://github.com/Stremio/stremio-web/issues/252

**Comment by hartontw** [comment]
My workaround to fix the cors issue is enabling https remote connections.

I've tested with this docker image and the script itself.

1. Connect to http://app.strem.io/shell-v4.4/?streamingServer=http://container-ip:11470
2. Login with your account
3. Settings -> Enable HTTPS remote connections
4. Copy endpoint url

**Comment by sleeyax** [comment]
Thanks for your suggestion but this issue refers to Stremio 5 (which is internally called `stremio-web`). 

I think the problem here is that the netlify domain isn't added to the CORS rules.

**Comment by sleeyax** [comment]
For reference: https://github.com/Stremio/stremio-web/issues/252#issuecomment-1008207607

**Comment by snowyyd** [comment]
I think the problem is because of this chunk of code in `server.js`:

```js
enginefs.router.use(function(req, res, next) {
    var ok = !req.headers.origin || req.headers.origin.match(".strem.io(\:80)?$") 
        || req.headers.origin.match(".stremio.net(\:80)?$")
        || req.headers.origin.match(".stremio.com(\:80)?$")
        || req.headers.origin.match("gstatic.com")
        || req.headers.origin === "https://stremio.github.io"
        || req.headers.origin.match("(127.0.0.1|localhost):11470$");
    if (ok) enginefs.sendCORSHeaders(req, res, next);
    else next();
});
```

The problem is in this line: `req.headers.origin.match("(127.0.0.1|localhost):11470$");`
It's because `req.headers.origin` returns the stremio-web port (default 8080) instead of 11470.

I fixed it on my docker config adding this line:
`RUN sed -i 's/if (ok) enginefs.sendCORSHeaders/if (1) enginefs.sendCORSHeaders/g' server/server.js`

I know that the fix is horrible because of the obvious `if (true)` and the if should be removed completely, but this fix is a one-line fix.

**Comment by sleeyax** [comment]
Thanks for your input.

The correct CORS headers according to a development branch should be:
```js
enginefs.router.use(function(req, res, next) {
    var ok = !req.headers.origin 
        || req.headers.origin.match(".strem.io(\:80)?$") 
        || req.headers.origin.match(".stremio.net(\:80)?$")
        || req.headers.origin.match(".stremio.com(\:80)?$")
        || req.headers.origin.match("stremio-development.netlify.app(\:80)?$")
        || req.headers.origin.match("stremio.github.io(\:80)?$")
        || req.headers.origin.match("gstatic.com")
        || req.headers.origin === "https://stremio.github.io/"
        || req.headers.origin.match("(127.0.0.1|localhost):11470$");
    if (ok) enginefs.sendCORSHeaders(req, res, next);
    else next();
});
```
At this point I'm only waiting for it to be merged with the master branch and published to `dl.stremio.*`. so this docker image can pull it.

**Comment by snowyyd** [comment]
So what about local instances of stremio-web?

**Comment by sleeyax** [comment]
Yeah I'm not sure what's up with that either tbh. See my comment here https://github.com/Stremio/stremio-web/issues/252#issuecomment-1052479215

Perhaps in the meantime we could implement your solution or similar (I'm not very familiar with sed) as a temporary fix? People have been waiting for an update for a while now, I think it's reasonable to add a  hack at this point. Feel free to create a PR.

**Comment by snowyyd** [comment]
Actually we can fix the actual regex for localhost to match any port (or none).

So this: `(127.0.0.1|localhost):11470$`
Becomes this: `(127.0.0.1|localhost)(:\d+)?$`

But I think CORS isn't needed at all for local instances, since we can use our custom domain or LAN IP for local instances (Think of something like http://raspberry:8080 for Raspberry Pi. This is my case).

About the use of `sed` (Stream EDitor) command, actually it can be used to edit files in place.

```
-i[SUFFIX], --in-place[=SUFFIX]
    edit files in place (makes backup if extension supplied). The default operation mode is to break symbolic and hard links. This can be changed with --follow-symlinks and --copy. 
```

```
s/regexp/replacement/
    Attempt to match regexp against the pattern space. If successful, replace that portion matched with replacement. The replacement may contain the special character & to refer to that portion of the pattern space which matched, and the special escapes \1 through \9 to refer to the corresponding matching sub-expressions in the regexp. 
```

`sed -i s/regexp/replacement/ <input file>`

Essentially, we are doing a regex match & replace.

man pages: https://linux.die.net/man/1/sed

Ofc I'll do a PR for you!

EDIT: @sleeyax take a look at this (https://github.com/n0bodysec/docker-images/blob/main/stremio-web/Dockerfile) to see my own implementation.

**Comment by sleeyax** [comment]
Looks good, personally I'd write it as `RUN sed -i 's/if (ok) enginefs.sendCORSHeaders/if (true) enginefs.sendCORSHeaders/g' server/server.js` though, it does the same thing but in my head `true` is syntactically cleaner in meaning than `1`.

**Comment by snowyyd** [comment]
Yeah, it looks cleaner. Anyway I tried to make the fix look "dirty" because it's a fix for a closed-source (?) library.

I'll do a PR now!

**Comment by Oredna** [comment]
I think this fix no longer works. I am having the same problem even after the if statement is changed to always be true.

**Comment by snowyyd** [comment]
> I think this fix no longer works. I am having the same problem even after the if statement is changed to always be true.

```js
enginefs.router.use(function(req, res, next) {
    var ok = process.env.NO_CORS ? true : !req.headers.origin || req.headers.origin.match(".strem.io(\:80)?$") 
        || req.headers.origin.match(".stremio.net(\:80)?$")
        || req.headers.origin.match(".stremio.com(\:80)?$")
        || req.headers.origin.match("gstatic.com")
        || req.headers.origin === "https://stremio.github.io"
        || req.headers.origin.match("(127.0.0.1|localhost):11470$")
        || req.headers.origin.match("peario.xyz");
    if (ok) enginefs.sendCORSHeaders(req, res, next);
    else next();
});
```

Latest versions of the server support the NO_CORS env var.
https://github.com/n0bodysec/docker-images/blob/main/stremio-web/docker-compose.yml#L14

**Comment by sleeyax** [comment]
@n0bodysec so they added this NO_CORS env variable support natively? Awesome. This docker image is still on the old version which is why it doesn't work. I need to make some changes to either revert back to specifying the server version via build args or pull in the latest version at runtime via a custom script.

**Comment by snowyyd** [comment]
> @n0bodysec so they added this NO_CORS env variable support natively? Awesome. This docker image is still on the old version which is why it doesn't work. I need to make some changes to either revert back to specifying the server version via build args or pull in the latest version at runtime via a custom script.

Yes, they added native support.

You may want to use build args (see [here](https://github.com/n0bodysec/docker-images/blob/main/stremio-web/Dockerfile#L7)). Downloading a copy of the server every start is not a good practice (high bandwidth usage, connection errors, necessary files no longer available on the server, etc). Also you can add some sort of cache or load the server from bind mounts. On my image, you can load your own custom version of the server.js by using bind mounts (for example, I run my own modified version of the server).

I have not yet pulled my docker image to the Docker hub. But you can check my repo for references.

**Comment by sleeyax** [comment]
> > @n0bodysec so they added this NO_CORS env variable support natively? Awesome. This docker image is still on the old version which is why it doesn't work. I need to make some changes to either revert back to specifying the server version via build args or pull in the latest version at runtime via a custom script.
> 
> Yes, they added native support.
> 
> You may want to use build args (see [here](https://github.com/n0bodysec/docker-images/blob/main/stremio-web/Dockerfile#L7)). Downloading a copy of the server every start is not a good practice (high bandwidth usage, connection errors, necessary files no longer available on the server, etc). Also you can add some sort of cache or load the server from bind mounts. On my image, you can load your own custom version of the server.js by using bind mounts (for example, I run my own modified version of the server).

Doesn't need to be on every start, I can have a default version and allow users to update the version within a running container by executing an update script that's stored in the container. 

I'll look into this mounts solution of yours.

**Comment by Oredna** [comment]
@sleeyax i will be forever grateful if you could fixed it one more time

**Comment by sleeyax** [comment]
> @sleeyax i will be forever grateful if you could fixed it one more time

I pushed changes yesterday. Pull in the latest image. NO_CORS should be enabled by default now, no more patch needed.

**Comment by Oredna** [comment]
@sleeyax not working for me, and i have the latest one. i tested on https://stremio-development.netlify.app/. Not working. it works on native apps (as it is localhost).

**Comment by snowyyd** [comment]
> @sleeyax not working for me, and i have the latest one. i tested on https://stremio-development.netlify.app/. Not working. it works on native apps (as it is localhost).

Can you try [this image](https://github.com/n0bodysec/docker-images/tree/main/stremio-web)? It should work.

**Comment by Oredna** [comment]
now it works but still giver error:

error 1
`Access to fetch at 'https://22.download.real-debrid.com/**(movie name)**' (redirected from 'https://torrentio.strem.fun/realdebrid/**(movie name)**) from origin 'https://stremio.**domain.com**' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
getContentType.js:10`

error 2
`HEAD https://22.download.real-debrid.com/d/(movie name) net::ERR_FAILED 200`

**Comment by snowyyd** [comment]
It works fine on my end. If you are using my docker image, it contains a bundled copy of Stremio Web that you can use (port 8080 by default).

**Comment by sleeyax** [comment]
> @sleeyax not working for me, and i have the latest one. i tested on [stremio-development.netlify.app](https://stremio-development.netlify.app/). Not working. it works on native apps (as it is localhost).

Oops, I messed up. I assumed triggering a rebuild would have upped the version to `v4.19.0`, but I totally forgot about docker cache which means the old version `v4.18.0` was still published instead.  I've disabled caching, so now it should work.
