### ISSUE TITLE
Patch scripts

### ISSUE THREAD

**Issue by sleeyax** [sleeyax/stremio-streaming-server#7]
I'm not sure how many patches I'd like to apply to the streaming server script by default, especially if potential side effects are unknown. Perhaps it makes more sense to include 'patch scripts' that users can apply at runtime if they chose to do so at their own risk of breaking it. By default it should apply no patches and there should be proper docs on how to apply them.

CC @n0bodysec

**Comment by snowyyd** [comment]
I'm working on a proper way rn

**Comment by sleeyax** [comment]
Thanks, really appreciate your help so far :muscle:

**Comment by snowyyd** [comment]
You are welcome!

Look at this: https://github.com/n0bodysec/docker-images/commit/cc4e60c0d8aa87561fd2a99c8ebda36bf413f9ba


> 'patch scripts' that users can apply at runtime

All patches should be applied in buildtime, not in runtime

**Comment by snowyyd** [comment]
Also I'm working on a way to "patch" the default installed addons, because the installed addons are stored in browser's local storage and the config cannot be shared (I had to reinstall my favorites addons on all my browsers/devices)

Anyway, this script should be done in a separate Dockerfile, because the way to add default addons is a big mess (I needed to edit stremio-official-addons repo and recompile all projects where stremio-official-addons is used). It also can be done in a docker-compose file.

**Comment by sleeyax** [comment]
I'd like users to be able to pull in the docker image from docker hub without having to clone and build from source themselves. If build arguments come into play, we'd need to publish 'multiple versions' of the same image by using different tags to docker hub. This might overcomplicate things and thus including the patches into the base container so they can be applied 'at runtime' as I mentioned might make more sense.

Way I see it atm is to just copy over a `patches` folder containing shell scripts with your `sed` commands. Then, users can apply whatever patches they want with `docker exec`.

**Comment by snowyyd** [comment]
Not exactly. You can define buildtime arguments in CLI ([reference](https://docs.docker.com/engine/reference/commandline/build/#options)).

```sh
docker build -t stremio --build-arg FIX_CORS=1 .
docker run -p 11470:11470 -v ${PWD}:/root/.stremio-server --name=stremio stremio
```

**Comment by sleeyax** [comment]
Yes, I know. What I mean is I kinda want to omit the build step so users only have to pull a prebuilt image from docker hub.

**Comment by sleeyax** [comment]
Though I didn't know you can build from a GitHub url now 🤔. 

Perhaps we can let users build from this gh repo url with the build arguments of their choice and only publish 2 docker images to docker hub: 1 default image with no patches and 1 with all patches applied.

**Comment by snowyyd** [comment]
Well, in this case you could opt for runtime scripts as you mentioned earlier.

You can change ARG (buildtime args) to ENV (buildtime & runtime env variables) and add the patch script to entrypoint.

So the users will be able to do something like this:

`docker run -p 11470:11470 -v ${PWD}:/root/.stremio-server --name=stremio-streaming-server -e FIX_CORS=1 sleeyax/stremio-streaming-server`

**Comment by sleeyax** [comment]
I'm just gonna keep the CORS patch as it is. If anyone wants to apply the 'unsupported media' patch as well, checkout https://github.com/n0bodysec/docker-images/blob/main/stremio-web/patches.sh and apply it yourself by cloning this repo or extending this docker image. I don't like to tinker too much with the original server.js source file.

**Comment by kvn1351** [comment]
> Yes, I know. What I mean is I kinda want to omit the build step so users only have to pull a prebuilt image from docker hub.

If you look at my pull request, I've implemented the usual "docker way" of dealing with this by applying patches at runtime that is controlled via ENV variables. These can be set by default as I did.

I'd add a bit of documentation for each ENV variable et voila' :).
