### ISSUE TITLE
[bug] Subtitle option is missing for shows

### ISSUE THREAD

**Issue by AndnixSH** [sleeyax/stremio-streaming-server#8]
**Describe the bug**
The subtitle option in the player bar is missing for shows, even the video supports it.
In the client version, there is subtitle option can be seen

Docker version
![image](https://user-images.githubusercontent.com/40742924/168445389-70d2a9b3-0311-477b-b504-a89a5b1815d1.png)

Client version (Windows)
![image](https://user-images.githubusercontent.com/40742924/168445410-23bbf137-c341-4747-8888-35d998704f16.png)

**Steps to Reproduce**
Watch any episodes of Court Cam and Cops. Check on client side too to confirm the issue

**Comment by sleeyax** [comment]
What addon(s) are you using? I can't immediately reproduce this and am getting subtitle errors as well with the streaming server that comes bundled with Stremio.

**Comment by AndnixSH** [comment]
> What addon(s) are you using? I can't immediately reproduce this and am getting subtitle errors as well with the streaming server that comes bundled with Stremio.

I use lots of addons. I got the same error too but i ignore it because subtitle is still working on client. The subtitle is embedded in video that streaming server can't read. Is it possible to support embedded subtitle?

![image](https://user-images.githubusercontent.com/40742924/176879789-0534e631-fca9-47b7-a2a1-8c8a1003f7ed.png)

![image](https://user-images.githubusercontent.com/40742924/176880028-e5a074ae-d79e-465f-97f5-698e867e5776.png)

**Comment by sleeyax** [comment]
Odd, I still can't reproduce this. 

Make sure you're on the latest version by stopping and deleting the container, removing the image and starting the container again:
```
$ docker stop stremio-streaming-server
$ docker rm stremio-streaming-server
$ docker rmi sleeyax/stremio-streaming-server
```

Embedded subs seem to be working fine on my end with the latest docker container running in the background as you can see below:

<img width="768" alt="image" src="https://user-images.githubusercontent.com/30344294/176981199-ebc48788-375e-4e08-93fb-8ad3eb442e52.png">

**Comment by AndnixSH** [comment]
I'm using ContainerStation by QNAP, it has option to download container from dockerhub directly. I tried removing and installing latest version you published 8 hours ago, still no subtitle. Also happen on Stremio 5 

![image](https://user-images.githubusercontent.com/40742924/176994679-24e10e55-f3dc-4e8a-8e19-0551eb7aa2ad.png)

![image](https://user-images.githubusercontent.com/40742924/176994734-17be03af-f43c-4bad-9bca-27196f7795e5.png)

**Comment by sleeyax** [comment]
Aha! That's important information. I'm not familiar with QNAP though. 

I don't see the movie/series getting requested in your streaming server logs (in the screenshot you provided). Are you sure the streaming server is even running properly?

**Comment by sleeyax** [comment]
Would it be possible for you to run the streaming server container locally on your computer (where stremio running)? Then at least we can confirm whether it's a QNAP specific issue.

**Comment by AndnixSH** [comment]
> Aha! That's important information. I'm not familiar with QNAP though.
> 
> I don't see the movie/series getting requested in your streaming server logs (in the screenshot you provided). Are you sure the streaming server is even running properly?

I'm not sure, still getting `GET /` without additional info even i opened movie with external subtitles. Everything else working fine beside embedded subtitles

**Comment by AndnixSH** [comment]
> Would it be possible for you to run the streaming server container locally on your computer (where stremio running)? Then at least we can confirm whether it's a QNAP specific issue.

Can't because I need to enable Hyper-V which beaks software I need. However, I can try running docker within Ubuntu inside QNAP but i'm not sure about its network. Last time i tried, i couldn't get port open due to NAT

**Comment by AndnixSH** [comment]
Same issue on ubuntu. I open stremio directly on ubuntu
![image](https://user-images.githubusercontent.com/40742924/176997012-7ca117db-164c-42e1-aeff-644168b91111.png)

**Comment by kvn1351** [comment]
I can't reproduce this issue.

**Comment by sleeyax** [comment]
> I can't reproduce this issue.

Are you using ContainerStation by QNAP?

**Comment by kvn1351** [comment]
No, I have only tested on Ubuntu. Should have specified.

**Comment by sleeyax** [comment]
Hmm this is likely an issue with QNAP then but since I don't have the system requirements to run that I can't reproduce this issue either, making it only more difficult to debug and solve...

**Comment by AndnixSH** [comment]
After numerous testing on different systems, different browsers and different VPN connections, it turns out it's the issue of the web version of app.strem.io. Also web version doesn't work well on iOS device, so the only way is to remote control my PC
 
Closing

**Comment by kvn1351** [comment]
> After numerous testing on different systems, different browsers and different VPN connections, it turns out it's the issue of the web version of app.strem.io. Also web version doesn't work well on iOS device, so the only way is to remote control my PC
> 
> Closing

Are you accessing stremio by containerIP:port or by app.strem.io with streamServer set to the right values?

Try to access it via containerIP:port because the webUI/server version will be different.

**Comment by AndnixSH** [comment]
> Are you accessing stremio by containerIP:port or by app.strem.io with streamServer set to the right values?
> 
> Try to access it via containerIP:port because the webUI/server version will be different.

I did, it redirects to app.strem.io, and same issue no matter what. I have given up
